fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

leboncoin:
    resource:  "@LeboncoinBundle/Resources/config/routing.yml"
    prefix:    /

annonces:
    resource:  "@AnnoncesBundle/Resources/config/routing.yml"
    prefix:    /Annonces

